config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, :description, :created_at, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :is_accomplished, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for(:title) %>
        <%= yield :title %>
      <% else %>
        My Todo
      <% end %>
    </title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "volt", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200">
    <div class="container">
      <div class="col-sm-11 py-6 col-md-9 mx-auto">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form|  %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-4">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", rows: "10" %>
  </div>


  <div class="form-check form-switch mb-4">
    <%= form.label :is_accomplished, class: "form-check-label" %>
    <%= form.check_box :is_accomplished, class: "form-check-input" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-outline-indigo" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p>
    <strong>Title:</strong>
    <%= todo.title %>
  </p>

  <p>
    <strong>Is accomplished:</strong>
    <%= todo.is_accomplished %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= todo.description %>
  </p>

</div>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo, class: "btn btn-primary" %>
  <%= link_to "Back to todos", todos_path, class: "btn btn-info" %>
</div>

app/views/todos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todos</h1>

<div id="todos">
  <% @todos.each do |todo| %>
    <div class="card border-0 shadow mb-4">
      <div class="card-header">
        <div class="row align-items-center">
          <div class="col"><h2 class="fs-5 fw-bold mb-0"><%= todo.title %></h2></div>
          <div class="col text-end">
            <%= todo.created_at %>
            <% if todo.is_accomplished %>
              <a href="#" class="btn btn-sm btn-success">Done!</a>
            <% else %>
              <a href="#" class="btn btn-sm btn-danger">UnDone!</a>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <p>
          <%= todo.description %>
        </p>
      </div>
      <div class="card-footer d-flex gap-2">
        <%= link_to "Show this todo", todo, class: "btn btn-outline-info" %>
        <%= link_to "Edit this todo", edit_todo_path(todo), class: "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to new_todo_path, class: "btn btn-outline-tertiary" do %>
  ↳ Add New
<% end %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<% content_for :title do %>
  <%= @todo.title %>
<% end %>
<p style="color: green"><%= notice %></p>

<div class="card border-0 shadow mb-4">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col"><h2 class="fs-5 fw-bold mb-0"><%= @todo.title %></h2></div>
      <div class="col text-end">
        <% if @todo.is_accomplished %>
          <a href="#" class="btn btn-sm btn-success">Done!</a>
        <% else %>
          <a href="#" class="btn btn-sm btn-danger">UnDone!</a>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-body">
    <p>
      <%= @todo.description %>
    </p>
  </div>
</div>
<div class="d-flex gap-2">
  <%= link_to "Edit this todo", edit_todo_path(@todo), class: "btn btn-outline-primary" %>
  <%= link_to "Back to todos", todos_path, class: "btn btn-outline-info" %>

  <%= button_to "Destroy this todo", @todo, method: :delete, class: "btn btn-outline-indigo" %>
</div>